export const INDIA_STATES_AND_UTS = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const MAJOR_DISTRICTS_BY_STATE = {
  'Andhra Pradesh': ['Anantapur', 'Chittoor', 'Guntur', 'Krishna', 'Kurnool', 'Nellore', 'Visakhapatnam', 'Vijayawada'],
  'Arunachal Pradesh': ['Tawang', 'Papum Pare', 'East Siang', 'Lower Subansiri', 'West Kameng'],
  Assam: ['Cachar', 'Dibrugarh', 'Kamrup Metropolitan', 'Jorhat', 'Nagaon', 'Sonitpur', 'Tinsukia'],
  Bihar: ['Bhagalpur', 'Darbhanga', 'Gaya', 'Muzaffarpur', 'Patna', 'Purnia', 'Vaishali'],
  Chhattisgarh: ['Bastar', 'Bilaspur', 'Durg', 'Korba', 'Raipur', 'Rajnandgaon'],
  Goa: ['North Goa', 'South Goa'],
  Gujarat: ['Ahmedabad', 'Bhavnagar', 'Gandhinagar', 'Jamnagar', 'Rajkot', 'Surat', 'Vadodara'],
  Haryana: ['Faridabad', 'Gurugram', 'Hisar', 'Karnal', 'Panipat', 'Rohtak', 'Sonipat'],
  'Himachal Pradesh': ['Chamba', 'Kangra', 'Kullu', 'Mandi', 'Shimla', 'Solan'],
  Jharkhand: ['Bokaro', 'Dhanbad', 'East Singhbhum', 'Hazaribagh', 'Ranchi', 'West Singhbhum'],
  Karnataka: ['Bengaluru Urban', 'Belagavi', 'Dakshina Kannada', 'Dharwad', 'Mysuru', 'Shivamogga', 'Tumakuru'],
  Kerala: ['Ernakulam', 'Kannur', 'Kollam', 'Kottayam', 'Kozhikode', 'Thiruvananthapuram', 'Thrissur'],
  'Madhya Pradesh': ['Bhopal', 'Gwalior', 'Indore', 'Jabalpur', 'Rewa', 'Sagar', 'Ujjain'],
  Maharashtra: ['Aurangabad', 'Nagpur', 'Nashik', 'Navi Mumbai', 'Pune', 'Thane', 'Mumbai'],
  Manipur: ['Bishnupur', 'Churachandpur', 'Imphal East', 'Imphal West', 'Thoubal'],
  Meghalaya: ['East Khasi Hills', 'Jaintia Hills', 'Ri-Bhoi', 'West Garo Hills'],
  Mizoram: ['Aizawl', 'Champhai', 'Kolasib', 'Lunglei', 'Serchhip'],
  Nagaland: ['Dimapur', 'Kohima', 'Mokokchung', 'Mon', 'Tuensang'],
  Odisha: ['Balasore', 'Cuttack', 'Ganjam', 'Khordha', 'Mayurbhanj', 'Sambalpur'],
  Punjab: ['Amritsar', 'Bathinda', 'Jalandhar', 'Ludhiana', 'Patiala', 'SAS Nagar', 'Tarn Taran'],
  Rajasthan: ['Ajmer', 'Alwar', 'Bikaner', 'Jaipur', 'Jaisalmer', 'Jodhpur', 'Kota', 'Udaipur'],
  Sikkim: ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Tiruchirappalli', 'Tirunelveli', 'Tiruppur'],
  Telangana: ['Adilabad', 'Hyderabad', 'Karimnagar', 'Khammam', 'Medak', 'Nalgonda', 'Rangareddy', 'Warangal'],
  Tripura: ['Dhalai', 'Gomati', 'North Tripura', 'South Tripura', 'West Tripura'],
  'Uttar Pradesh': ['Agra', 'Allahabad', 'Ghaziabad', 'Gorakhpur', 'Hapur', 'Kanpur Nagar', 'Lucknow', 'Meerut', 'Noida', 'Varanasi'],
  Uttarakhand: ['Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Udham Singh Nagar', 'Uttarkashi'],
  'West Bengal': ['Darjeeling', 'Howrah', 'Hooghly', 'Kolkata', 'Nadia', 'North 24 Parganas', 'South 24 Parganas'],
  'Andaman and Nicobar Islands': ['South Andaman', 'North and Middle Andaman', 'Nicobar'],
  Chandigarh: ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Dadra and Nagar Haveli', 'Daman', 'Diu'],
  Delhi: ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'South Delhi', 'West Delhi'],
  'Jammu and Kashmir': ['Anantnag', 'Baramulla', 'Jammu', 'Kathua', 'Srinagar', 'Udhampur'],
  Ladakh: ['Leh', 'Kargil'],
  Lakshadweep: ['Agatti', 'Kavaratti', 'Minicoy'],
  Puducherry: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
};
