/**
 * Frontend RBAC — UI visibility only.
 * Backend remains authoritative for actual access control.
 */

export const ROLES = {
  CENTRAL_OFFICER: 'CENTRAL_OFFICER',
  STATE_OFFICER: 'STATE_OFFICER',
  DISTRICT_OFFICER: 'DISTRICT_OFFICER',
  FIELD_OFFICER: 'FIELD_OFFICER',
};

export const ROLE_LABELS = {
  CENTRAL_OFFICER: 'Central Officer',
  STATE_OFFICER: 'State Officer',
  DISTRICT_OFFICER: 'District Officer',
  FIELD_OFFICER: 'Field Officer',
};

export const ROLE_COLORS = {
  CENTRAL_OFFICER: 'bg-navy-100 text-navy-700',
  STATE_OFFICER: 'bg-purple-100 text-purple-700',
  DISTRICT_OFFICER: 'bg-blue-100 text-blue-700',
  FIELD_OFFICER: 'bg-teal-100 text-teal-700',
};

export function getRoleLabel(role) {
  return ROLE_LABELS[role] || role;
}

export function getRoleColor(role) {
  return ROLE_COLORS[role] || 'bg-slate-100 text-slate-600';
}

// Feature visibility
export function can(role, action) {
  const perms = {
    CREATE_PROJECT: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER],
    EDIT_PROJECT: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER, ROLES.DISTRICT_OFFICER],
    WORKFLOW_TRANSITION: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER, ROLES.DISTRICT_OFFICER],
    RECORD_PAYMENT: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER, ROLES.DISTRICT_OFFICER],
    RESOLVE_OBJECTION: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER, ROLES.DISTRICT_OFFICER],
    UPDATE_RNR: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER, ROLES.DISTRICT_OFFICER, ROLES.FIELD_OFFICER],
    UPLOAD_DOCUMENT: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER, ROLES.DISTRICT_OFFICER, ROLES.FIELD_OFFICER],
    VIEW_AUDIT: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER, ROLES.DISTRICT_OFFICER],
    VIEW_ALL_PROJECTS: [ROLES.CENTRAL_OFFICER],
    VIEW_STATE_PROJECTS: [ROLES.CENTRAL_OFFICER, ROLES.STATE_OFFICER],
  };
  if (!perms[action]) return true; // default allow for unknown actions
  return perms[action].includes(role);
}
